name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Setup Environment Variables
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Setup Service Account
        run: echo '${{ secrets.SERVICE_ACCOUNT }}' > src/Config/serviceaccount.json

      - name: Setup Clasp
        run: echo '${{ secrets.CLASPRC_CREDENTIALS }}' > $HOME/.clasprc.json

      - name: Install Dependencies
        run: npm ci

      - name: Lint Project
        run: npm run lint

      - name: Build Project
        run: npm run build
